service: kendricklamar
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
functions:
  receive:
    handler: handler.receive
    events:
      - http:
          path: receive
          method: post
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-Pillow:7
